CREATE TABLE
  IF NOT EXISTS items (name TEXT PRIMARY KEY, category TEXT, data BLOB NOT NULL) WITHOUT ROWID;

CREATE TABLE
  IF NOT EXISTS inventories (inventoryId TEXT PRIMARY KEY, type TEXT, data BLOB NOT NULL) WITHOUT ROWID;

CREATE TABLE
  IF NOT EXISTS inventory_items (uniqueId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, inventoryId TEXT NULL, data BLOB NOT NULL);

CREATE INDEX IF NOT EXISTS category ON items (category);

CREATE INDEX IF NOT EXISTS type ON inventories (type);

CREATE INDEX IF NOT EXISTS inventoryId ON inventory_items (inventoryId);
